// examples/vue/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { authClient } from "./lib/auth-client";

const session = authClient.useSession();
const email = ref("vue@example.com");
const password = ref("password123");
const message = ref<string | null>(null);

async function signIn() {
  const { error } = await authClient.signIn.email({ email: email.value, password: password.value });
  message.value = error ? error.message ?? "Sign in failed" : "Signed in";
}

async function signOut() {
  await authClient.signOut();
  message.value = "Signed out";
}
</script>

<template>
  <main style="font-family: system-ui; max-width: 32rem; margin: 2rem auto; padding: 1rem">
    <p style="opacity: 0.7">better-auth/vue → Go server</p>
    <h1>Vue client example</h1>
    <p v-if="session.isPending">Loading session…</p>
    <p v-else-if="session.data">Hello, {{ session.data.user.email }}</p>
    <p v-else>Not signed in</p>
    <form @submit.prevent="signIn" style="display: grid; gap: 0.5rem; margin-top: 1rem">
      <input v-model="email" type="email" placeholder="Email" required />
      <input v-model="password" type="password" placeholder="Password" required />
      <button type="submit">Sign in</button>
      <button type="button" @click="signOut">Sign out</button>
    </form>
    <p v-if="message">{{ message }}</p>
  </main>
</template>

// examples/expo/app/index.tsx
import { useEffect, useState } from "react";
import { Button, Text, TextInput, View } from "react-native";
import { authClient } from "../lib/auth-client";

export default function Home() {
  const { data: session, isPending, refetch } = authClient.useSession();
  const [email, setEmail] = useState("expo@example.com");
  const [password, setPassword] = useState("password123");
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    void refetch();
  }, [refetch]);

  return (
    <View style={{ flex: 1, justifyContent: "center", padding: 24, gap: 8 }}>
      <Text style={{ fontSize: 22, fontWeight: "600" }}>Expo + Better Auth (Go)</Text>
      <Text>Bearer token auth for mobile — enable plugins.Bearer on the server.</Text>
      {isPending ? (
        <Text>Loading session…</Text>
      ) : session ? (
        <Text>Signed in as {session.user.email}</Text>
      ) : (
        <Text>Not signed in</Text>
      )}
      <TextInput value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" />
      <TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry />
      <Button
        title="Sign in"
        onPress={async () => {
          const { error } = await authClient.signIn.email({ email, password });
          setMessage(error ? (error.message ?? "Failed") : "Signed in");
          await refetch();
        }}
      />
      <Button
        title="Sign out"
        onPress={async () => {
          await authClient.signOut();
          setMessage("Signed out");
          await refetch();
        }}
      />
      {message ? <Text>{message}</Text> : null}
    </View>
  );
}
